//设置店铺财务详情信息
export const SET_SHOP_FINANCE_DETAILS = 'SET_SHOP_FINANCE_DETAILS'
export const SET_TIME_FRAME = 'SET_TIME_FRAME'
export const SET_SHOP_PROFIT_LIST = 'SET_SHOP_PROFIT_LIST'
export const SET_SHOP_OPTIONS = 'SET_SHOP_OPTIONS'
export const SET_SHOP_ID = 'SET_SHOP_ID'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_NOTICE_LIST = 'SET_NOTICE_LIST'